### PR TITLE
patch for HullCameraVDS

### LINKED ISSUE #56: [Request]: patch for HullCameraVDS
### Description of the new feature / enhancement

add a compatibility patch for hullcam

### Proposed technical implementation details

1. create the patch

### PR DESCRIPTION
**Pull request by FuryFire2004**
# patch for HullCameraVDS

* create issue (#56)
* create [HullCameraVDS.cfg]
* Header/Footer (will be added by @zer0Kerbal )
* thank you to @FuryFire2004 
* closes #56 - [Request]: patch for hullcam #56

### CODE REVIEW

**Review by FuryFire2004 — COMMENTED** [review]
im biased

**Review by zer0Kerbal — APPROVED** [review]
🧧

**Comment by FuryFire2004** [comment]
> 🧧

**Comment by zer0Kerbal** [comment]
I updated the above information because it becomes part of the permanent changelog.md (through automation)
thank you - will review/merge more later. time for errands. BBL

**Pull request merged**
