### PR TITLE
CLS Compatability patch

### LINKED ISSUE #57: [Request]: patch for ConnectedLivingSpaces (CLS)
### Description of the new feature / enhancement

add a compatibility patch for patch for ConnectedLivingSpaces (CLS)

### Proposed technical implementation details

1. create the patch [ConnectedLivingSpaces.cfg]

### PR DESCRIPTION
**Pull request by FuryFire2004**
# patch for ConnectedLivingSpaces (CLS)

* create issue (#56)
* create [ConnectedLivingSpaces.cfg]
* Header/Footer (will be added by @zer0Kerbal )
* thank you to @FuryFire2004 
* closes #57 - [Request]: patch for ConnectedLivingSpaces (CLS) #57

### CODE REVIEW

**Review by FuryFire2004 — COMMENTED** [review]
biased review

**Comment by FuryFire2004** [comment]
did i do the wrong parts or something?

**Comment by FuryFire2004** [comment]
there are duplicates so its possible i did

**Review by zer0Kerbal — APPROVED** [review]
👾

**Comment by zer0Kerbal** [comment]
> did i do the wrong parts or something?

all good - except trying to PR into `master` branch. ;p

**Pull request merged**
