### PR TITLE
added compatability for habtech ports, should work given commas work with ports

### PR DESCRIPTION
**Pull request by FuryFire2004**
this means you can dock your dreamer to your ISS CMB from habtech2 allowing you to do the real planned resupply missions!

### CODE REVIEW

**Review by FuryFire2004 — COMMENTED** [review]
ya

**Comment by FuryFire2004** [comment]
what are jobs and why are they awakening me for a second time now

**Comment by FuryFire2004** [comment]
Btw I have not had time to load this up and check it because my grandpa kinda had a stroke and all that...

**Comment by zer0Kerbal** [comment]
@FuryFire2004 I am thinking since this is a mod compatibility item, that it belongs in a Compatibility patch
```
@PART[drm-nose-dock]:NEEDS[HabTech2,Dreamer]:FOR[Dreamer]
{
  @MODULE[ModuleDockingNode]
  {
// for HT-PMA Pressurised Mating Adapter
    @nodeType ^= :$:, B10_APAS:
  }
}

@PART[drm-dock-rear]:NEEDS[HabTech2,Dreamer]:FOR[Dreamer]
{
  @MODULE[ModuleDockingNode]
  {
// for C-200 Common Berthing Mechanism [ht2_CBM]  ht2_CBM
    @nodeType ^= :$:, ht2_CBM:
  }
}
```
This way keep compatibility separate from parts. what do you think? Plus the patch becomes a template for other mods like NFC etc.

**Comment by FuryFire2004** [comment]
Yea that is def the better way lel

**Comment by FuryFire2004** [comment]
I think I should test that config tommarow given I currently have habtech installed

**Comment by FuryFire2004** [comment]
I can start craping out patches for random mods tommarow if you want me to using this config as a framework

**Review by zer0Kerbal — APPROVED** [review]

**Comment by zer0Kerbal** [comment]
> what are jobs and why are they awakening me for a second time now

@FuryFire2004 they are located under .github/workflows and automated processes that occur when specific things happen. Example - a commit .

**Comment by zer0Kerbal** [comment]
> Btw I have not had time to load this up and check it because my grandpa kinda had a stroke and all that...
@FuryFire2004 
# Real Life First; family before all; 

## ***sympathies and hopes of speedy and total recovery. ***

**Comment by FuryFire2004** [comment]
i made a clean patch for the reer docking port to have a hullcam

**Comment by FuryFire2004** [comment]
closisng

**Pull request closed without merging**
