### PR TITLE
Create mechjeb patch

### LINKED ISSUE #58: [Request]: patch for MechJeb (MJ)
### Description of the new feature / enhancement

add a compatibility patch for patch for MechJeb (MJ)

### Proposed technical implementation details

1. create the patch [MechJeb.cfg]

### PR DESCRIPTION
**Pull request by FuryFire2004**
# patch for MechJeb (MJ)

* create issue (#58 )
* create [MechJeb.cfg]
* Header/Footer (will be added by @zer0Kerbal )
* thank you to @FuryFire2004 
* closes #58  - [Request]: patch for MechJeb (MJ)

### CODE REVIEW

**Review by FuryFire2004 — COMMENTED** [review]
biased.jpg

**Comment by FuryFire2004** [comment]
image
this is what caused me to write this

**Comment by zer0Kerbal** [comment]
*chuckle* not my screenshot - but I see it there. :)

**Review by zer0Kerbal — APPROVED** [review]
🤖

**Pull request merged**
